### ISSUE TITLE
iOS app : profile photos and part of cover photos in circle area show in feed both not just profile photo see pics

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/mobile-app-issues#14]
# Important

Please follow this template!

----------------------------------------

## What's happened?

... when you view the profile pics that show in the feed after user uploads or updates, the circle area also shows part of the cover photo as well. see photos

## Steps to reproduce:
1. user uploads profile picture
2. or user updates profile picture
3. see photos below

## What's expected?

... should only show profile photo in feed not part of the cover photo 

## OS and Devices tested
(Example: Android, iOS, iPhone, Galaxy Note...)

...iOS iPhone 12 max pro iOS 14

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 nginx php-fpm 7.4 

## phpFox version
(Example: phpFox 4.6.0)
4.8.1 fresh install 
...

## APIs and App version
RESTful Api 4.24
Mobile Api 4.6.2
App version from apple store - 1.7.2
...

## Screenshots
...
![image](https://user-images.githubusercontent.com/17736688/96819625-a87cf000-13e9-11eb-80b6-8f43d1c999a4.png)
![image](https://user-images.githubusercontent.com/17736688/96819639-b16dc180-13e9-11eb-9e6c-1b405741b2c6.png)

**Comment by tonyphpfox** [comment]
Hi @spirogg 
I'll discuss with team about this request and reply to you later.

Regards.

**Comment by tonyphpfox** [comment]
Hi @spirogg 
We'll implement this improvement in next version.

Regards.

**Comment by spirogg** [comment]
@tonyphpfox 

Thank you 
Regards,
Spiro

**Comment by spirogg** [comment]
@tonyphpfox has this been implemented yet. Thanks for your reply in advance

**Comment by tonyphpfox** [comment]
> @tonyphpfox has this been implemented yet. Thanks for your reply in advance

Hi @spirogg,
This improvement was added in version 1.7.4.

Regards.
