### ISSUE TITLE
when we upload video in iOS app can we make the title section larger - right now its really small area to input title

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/mobile-app-issues#19]
# Important

Please follow this template!

----------------------------------------

## What's happened?

**Using iOS app 1.7.2** 

- when users upload a video in iOS app, the title space we have to type in a title for that video is too small....
can we make the title (input section) larger (height) - right now the height is really small area to input title and sometimes users don't see that you suppose to add title there.

needs to be height bigger to be able to see, especially if user has hard time or needs glasses.

thanks
...

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?

...

## OS and Devices tested
(Example: Android, iOS, iPhone, Galaxy Note...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## APIs and App version

...

## Screenshots
...
![image](https://user-images.githubusercontent.com/17736688/97368907-e1014b80-1879-11eb-9aa5-41ff2ad4312d.png)

**Comment by tonyphpfox** [comment]
Hi @spirogg 
I've checked Create Post Screen. As a normal user, I can see that title section is really small on an iPhone 11 screen, and sometimes title section feel unresponsive due to small pressable area.
Thank you for your report.

Regards

**Comment by spirogg** [comment]
@tonyphpfox tha k you again for this. 

Regards,
Spiro
