### ISSUE TITLE
Post text being cut off

### ISSUE THREAD

**Issue by karlkunc** [PHPfox-Official/mobile-app-issues#24]
# Important

Please follow this template!

----------------------------------------

## What's happened?

...when posting a comment or post the last line is not displayed sometimes. But if you edit the post the last line is displayed int he edit screen

## Steps to reproduce:
1. Posted a comment
2. Posted a comment on two different sites mobile app build
3. Last line randomly disappears on all sites

## What's expected? Comment to always be displayed

...

## OS and Devices tested
(Example: Android, iOS, iPhone, Galaxy Note...)

... android but I have seen it from many of my users so many different versions of Android. 

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos7

## phpFox version
(Example: phpFox 4.6.0)

...4.8.2

## APIs and App version

...1.7.2 or whatever the latest version is

## Screenshots
...
As you can see in the screenshots the edit version of the text is different than the visual version of the post.
![Screenshot_20210104-202206_Silority](https://user-images.githubusercontent.com/74743076/103595896-a0056300-4eca-11eb-86b5-c7f69ca05e3f.jpg)
![Screenshot_20210104-202221_Silority](https://user-images.githubusercontent.com/74743076/103595909-a72c7100-4eca-11eb-8a2c-8219968000bd.jpg)

**Comment by tonyphpfox** [comment]
Hi @karlkunc
This is a bug and we'll fix it soon.

Regards.
