### ISSUE TITLE
Quizzes results not showing on iOS and android apps

### ISSUE THREAD

**Issue by liviufox** [PHPfox-Official/mobile-app-issues#27]
on android and ios apps I can't see the results of any user that took any quizz
if you go on quizzes section and you choose any quizz then at the bottom you can't see the "recent plays" section
On the mobile version tested on chrome and safari that section is present

Core Version: | 4.8.4
-- | --
PHP Version: | 7.4.16
PHP Sapi: | litespeed
PHP safe_mode: | False
PHP open_basedir: | False
PHP Disabled Functions: | None
PHP Loaded Extensions: | Core date libxml openssl pcre sqlite3 zlib bz2 calendar ctype curl hash filter ftp gettext gmp SPL iconv pcntl readline Reflection session standard shmop SimpleXML mbstring tokenizer xml litespeed bcmath dba dom enchant fileinfo gd gmagick igbinary imap intl json ldap exif memcached mongodb mysqli mysqlnd odbc PDO pdo_mysql PDO_ODBC pdo_pgsql pdo_sqlite pgsql Phar posix pspell redis snmp soap sockets sysvmsg sysvsem sysvshm tidy xmlreader xmlrpc xmlwriter xsl zip Zend OPcache
Operating System: | Linux
Server Timestamp: | June 8, 2021, 7:50 am (GMT)
GZIP: | Enabled
SQL Driver Version: | MySQL 5.7.34-log
SQL Slave Enabled: | No
SQL Total Slaves: | N/A
SQL Slave Server: | N/A
Memory Limit: | 0.5 b (-1)
Load Balancing Enabled: | No
Total Server Memory: | 64424 MB
Available Server Memory: | 7171 MB
Current Server Load: | 8.66

**Comment by liviufox** [comment]
But why to have this option "only" if you have participated in the quiz? But you can easily see other results on desktop and mobile version?

**Comment by harrison05** [comment]
Yes, on the web version, we have a block that allows users to view other results (they only can see detailed answers of others if they played it or setting "f this option is enabled members of this user group will be able to view what other users answered in a quiz before they answer the quiz themselves." is enabled for their user group). So, we will check and improve the mobile app to make it has a workflow like web.

Regards.

**Comment by liviufox** [comment]
yes, please consider that block for the apps too. I can see my members are using that quizz section often and would be nice to have that block visible inside the apps too.
