### ISSUE TITLE
pictures looks like croped when loaded on iOS and android

### ISSUE THREAD

**Issue by liviufox** [PHPfox-Official/mobile-app-issues#28]
when a user uploads a pictures with a format like the one for instagram- taken with the phone not in landscape mode- the preview of the picture in the upload dialog is shown like the pictured is croped and it seems like it will be uploaded croped.
The end results is good but the user experience is like the app is croping the picture before uploading

Core Version: | 4.8.4
-- | --
PHP Version: | 7.4.16
PHP Sapi: | litespeed
PHP safe_mode: | False
PHP open_basedir: | False
PHP Disabled Functions: | None
PHP Loaded Extensions: | Core date libxml openssl pcre sqlite3 zlib bz2 calendar ctype curl hash filter ftp gettext gmp SPL iconv pcntl readline Reflection session standard shmop SimpleXML mbstring tokenizer xml litespeed bcmath dba dom enchant fileinfo gd gmagick igbinary imap intl json ldap exif memcached mongodb mysqli mysqlnd odbc PDO pdo_mysql PDO_ODBC pdo_pgsql pdo_sqlite pgsql Phar posix pspell redis snmp soap sockets sysvmsg sysvsem sysvshm tidy xmlreader xmlrpc xmlwriter xsl zip Zend OPcache
Operating System: | Linux
Server Timestamp: | June 8, 2021, 8:04 am (GMT)
GZIP: | Enabled
SQL Driver Version: | MySQL 5.7.34-log
SQL Slave Enabled: | No
SQL Total Slaves: | N/A
SQL Slave Server: | N/A
Memory Limit: | 0.5 b (-1)
Load Balancing Enabled: | No
Total Server Memory: | 64424 MB
Available Server Memory: | 3908 MB
Current Server Load: | 8.05

**Comment by tonyphpfox** [comment]
Hi @liviufox,
We will make some changes for better UX to solve this issue.
Regards.
